### ISSUE TITLE
BUMPDN supported as BUMPDOWN

### ISSUE THREAD

**Issue by sixlettervariables** [AlanDeSmet/human-resource-machine-viewer#2]
It appears that BUMPDOWN is what your parser expects rather than BUMPDN.

**Comment by AlanDeSmet** [comment]
Merci! Turns out none of the test programs I was using happened to use it.

**Comment by sixlettervariables** [comment]
De rien! Thank you for such a great tool. It was easy to integrate (working
on styling).
