### ISSUE TITLE
Bug with line couning if first line is a comment not equal to -- HUMAN RESOURCE MACHINE PROGRAM --

### ISSUE THREAD

**Issue by caco3** [AlanDeSmet/human-resource-machine-viewer#7]
Hi

I think I found a bug with the line counting in `setActiveLine()`

As far as I can see, if the first line contains `-- HUMAN RESOURCE MACHINE PROGRAM --`, it gets not shown and not counted.
However, if the first line is a comment with any other text, it gets shown, but not counted.
In the following example, I set the 5th line as active (`setActiveLine(5)`), but `OUTBOX` gets highlighted.

``` javascript
-- Test with invalid line count
INBOX 
COPYTO 1
SUB 0
SUB 2
OUTBOX
COPYFROM 0
```

**Comment by AlanDeSmet** [comment]
setActiveLine is counting all lines, including comments, including the special "-- HUMAN RESOURCE MACHINE PROGRAM --". It also indexes from 0.  My thinking is that it's the one form of counting both my code and someone else's code can be certain to agree on.

I tried a variety of things, and I got the behavior I was expecting. For your example I would expect OUTBOX to be highlighted. If you're not seeing behavior that matches my description above, please let me know; I'd consider it a bug I should fix.

If you think it should have different behavior, I'd be interested in hearing what you're thinking.

Either way, thanks for letting me know!

**Comment by caco3** [comment]
Thank you for looking into it.
I tried to reproduce it again myself but failed.
It might be that I had a bug in my surrounding code leading to my guess.
As is now, it seems all to be ok.
